"""Registry tujuh jenis surat dan kontrak field-nya."""

from __future__ import annotations

from typing import Any


JENIS_SURAT: dict[str, dict[str, Any]] = {
    "izin_guru": {
        "label": "Surat Permohonan Izin",
        "deskripsi": "Permohonan izin tidak masuk kerja bagi Guru / Staff SMADA.",
        "kategori": "guru",
        "icon": "fa-clipboard-user",
        "badge": "Izin Kerja",
        "template": "izin_guru.docx",
        "default_kode": "800.1.11",
        "signer": "pemohon",
        "context_defaults": {"unit_kerja": "SMA Negeri 2 Wonosari"},
        "fields": [
            {"name": "tanggal_mulai", "label": "Tanggal Mulai Izin", "type": "date"},
            {"name": "tanggal_selesai", "label": "Tanggal Selesai Izin", "type": "date"},
            {"name": "keperluan", "label": "Keperluan", "type": "text", "max_length": 300},
        ],
    },
    "cuti_guru": {
        "label": "Surat Permohonan Cuti",
        "deskripsi": "Permohonan cuti tahunan, sakit, melahirkan, atau alasan penting.",
        "kategori": "guru",
        "icon": "fa-calendar-minus",
        "badge": "Cuti Resmi",
        "template": "cuti_guru.docx",
        "default_kode": "800.1.11.4",
        "signer": "pemohon",
        "fields": [
            {
                "name": "jenis_cuti",
                "label": "Jenis Cuti",
                "type": "select",
                "options": [
                    "Cuti Tahunan",
                    "Cuti Sakit",
                    "Cuti Melahirkan",
                    "Cuti Besar",
                    "Cuti Alasan Penting",
                ],
            },
            {
                "name": "lama_cuti",
                "label": "Lama Cuti",
                "type": "text",
                "placeholder": "cth: 3 hari",
                "max_length": 80,
            },
            {"name": "tanggal_mulai", "label": "Terhitung Mulai Tanggal", "type": "date"},
            {"name": "tanggal_selesai", "label": "Sampai Dengan Tanggal", "type": "date"},
            {"name": "keperluan", "label": "Alasan Cuti", "type": "text", "max_length": 300},
            {
                "name": "alamat_selama_cuti",
                "label": "Alamat Selama Cuti",
                "type": "text",
                "max_length": 500,
            },
        ],
    },
    "sakit_guru": {
        "label": "Surat Pemberitahuan Sakit",
        "deskripsi": "Pemberitahuan resmi izin tidak masuk kerja dikarenakan sakit.",
        "kategori": "guru",
        "icon": "fa-user-nurse",
        "badge": "Izin Sakit",
        "template": "sakit_guru.docx",
        "default_kode": "800.1.11.2",
        "signer": "pemohon",
        "context_defaults": {"unit_kerja": "SMA Negeri 2 Wonosari"},
        "fields": [
            {"name": "tanggal_mulai", "label": "Tanggal Mulai Sakit", "type": "date"},
            {"name": "tanggal_selesai", "label": "Sampai Dengan Tanggal", "type": "date"},
            {
                "name": "keperluan",
                "label": "Keterangan Tambahan",
                "type": "text",
                "placeholder": "cth: demam tinggi",
                "max_length": 300,
            },
        ],
    },
    "surat_tugas_guru": {
        "label": "Surat Tugas Penugasan",
        "deskripsi": "Surat tugas resmi Kepala Sekolah untuk perjalanan / tugas dinas.",
        "kategori": "guru",
        "icon": "fa-briefcase",
        "badge": "Dinas SMADA",
        "template": "3. Surat Tugas-smada.docx",
        "default_kode": "800.1.11.1",
        "signer": "kepsek",
        "fields": [
            {"name": "tanggal_mulai", "label": "Tanggal Tugas", "type": "date"},
            {"name": "tanggal_selesai", "label": "Sampai Tanggal", "type": "date"},
            {
                "name": "keperluan",
                "label": "Uraian Tugas / Dasar",
                "type": "text",
                "max_length": 500,
            },
        ],
    },
    "surat_keterangan_guru": {
        "label": "Surat Keterangan Resmi",
        "deskripsi": "Surat keterangan aktif / penugasan resmi dari Kepala Sekolah.",
        "kategori": "guru",
        "icon": "fa-file-signature",
        "badge": "Keterangan",
        "template": "11. Surat Keterangan-smada.docx",
        "default_kode": "800.1.11",
        "signer": "kepsek",
        "fields": [
            {"name": "tanggal_mulai", "label": "Tanggal Keterangan", "type": "date"},
            {
                "name": "keperluan",
                "label": "Menerangkan Bahwa",
                "type": "text",
                "max_length": 500,
            },
        ],
    },
    "izin_murid": {
        "label": "Surat Izin Tidak Masuk",
        "deskripsi": "Pemberitahuan izin tidak masuk sekolah dari orang tua / wali murid.",
        "kategori": "murid",
        "icon": "fa-user-graduate",
        "badge": "Izin Siswa",
        "template": "izin_murid.docx",
        "default_kode": "400.3.8.9",
        "signer": "wali",
        "fields": [
            {"name": "nama_wali", "label": "Nama Orang Tua/Wali", "type": "text", "max_length": 120},
            {"name": "tanggal_mulai", "label": "Tanggal Mulai Izin", "type": "date"},
            {"name": "tanggal_selesai", "label": "Tanggal Selesai Izin", "type": "date"},
            {
                "name": "keperluan",
                "label": "Keperluan/Alasan",
                "type": "text",
                "max_length": 300,
            },
        ],
    },
    "dispensasi_murid": {
        "label": "Surat Dispensasi Kegiatan",
        "deskripsi": "Izin dispensasi mengikuti kegiatan lomba, OSIS, atau dinas luar.",
        "kategori": "murid",
        "icon": "fa-award",
        "badge": "Dispensasi",
        "template": "dispensasi_murid.docx",
        "default_kode": "400.3.8.10",
        "signer": "kepsek",
        "max_people": 3,
        "fields": [
            {"name": "nama_kegiatan", "label": "Nama Kegiatan", "type": "text", "max_length": 200},
            {"name": "penyelenggara", "label": "Penyelenggara", "type": "text", "max_length": 200},
            {"name": "tempat_kegiatan", "label": "Tempat Kegiatan", "type": "text", "max_length": 200},
            {"name": "tanggal_mulai", "label": "Tanggal Mulai", "type": "date"},
            {"name": "tanggal_selesai", "label": "Tanggal Selesai", "type": "date"},
            {
                "name": "keperluan",
                "label": "Uraian / Keperluan",
                "type": "text",
                "default": "Mengikuti kegiatan sebagaimana tersebut di atas",
                "max_length": 500,
            },
        ],
    },
}
