"""Registry jenis surat bawaan dan kontrak field-nya."""

from __future__ import annotations

from typing import Any


JENIS_SURAT: dict[str, dict[str, Any]] = {
    "izin_guru": {
        "label": "Surat Permohonan Izin",
        "deskripsi": "Permohonan izin tidak masuk kerja bagi Guru / Staff SMADA.",
        "kategori": "guru",
        "icon": "fa-clipboard-user",
        "badge": "Izin Kerja",
        "template": "izin_guru.docx",
        "default_kode": "800.1.11",
        "signer": "pemohon",
        "context_defaults": {"unit_kerja": "SMA Negeri 2 Wonosari"},
        "fields": [
            {"name": "tanggal_mulai", "label": "Tanggal Mulai Izin", "type": "date"},
            {"name": "tanggal_selesai", "label": "Tanggal Selesai Izin", "type": "date"},
            {"name": "keperluan", "label": "Keperluan", "type": "text", "max_length": 300},
        ],
    },
    "cuti_guru": {
        "label": "Surat Permohonan Cuti",
        "deskripsi": "Permohonan cuti tahunan, sakit, melahirkan, atau alasan penting.",
        "kategori": "guru",
        "icon": "fa-calendar-minus",
        "badge": "Cuti Resmi",
        "template": "cuti_guru.docx",
        "default_kode": "800.1.11.4",
        "signer": "pemohon",
        "fields": [
            {
                "name": "jenis_cuti",
                "label": "Jenis Cuti",
                "type": "select",
                "options": [
                    "Cuti Tahunan",
                    "Cuti Sakit",
                    "Cuti Melahirkan",
                    "Cuti Besar",
                    "Cuti Alasan Penting",
                ],
            },
            {
                "name": "lama_cuti",
                "label": "Lama Cuti",
                "type": "text",
                "placeholder": "cth: 3 hari",
                "max_length": 80,
            },
            {"name": "tanggal_mulai", "label": "Terhitung Mulai Tanggal", "type": "date"},
            {"name": "tanggal_selesai", "label": "Sampai Dengan Tanggal", "type": "date"},
            {"name": "keperluan", "label": "Alasan Cuti", "type": "text", "max_length": 300},
            {
                "name": "alamat_selama_cuti",
                "label": "Alamat Selama Cuti",
                "type": "text",
                "max_length": 500,
            },
        ],
    },
    "sakit_guru": {
        "label": "Surat Pemberitahuan Sakit",
        "deskripsi": "Pemberitahuan resmi izin tidak masuk kerja dikarenakan sakit.",
        "kategori": "guru",
        "icon": "fa-user-nurse",
        "badge": "Izin Sakit",
        "template": "sakit_guru.docx",
        "default_kode": "800.1.11.2",
        "signer": "pemohon",
        "context_defaults": {"unit_kerja": "SMA Negeri 2 Wonosari"},
        "fields": [
            {"name": "tanggal_mulai", "label": "Tanggal Mulai Sakit", "type": "date"},
            {"name": "tanggal_selesai", "label": "Sampai Dengan Tanggal", "type": "date"},
            {
                "name": "keperluan",
                "label": "Keterangan Tambahan",
                "type": "text",
                "placeholder": "cth: demam tinggi",
                "max_length": 300,
            },
        ],
    },
    "surat_tugas_guru": {
        "label": "Surat Perintah / Surat Tugas",
        "deskripsi": "Perintah resmi kepada satu atau banyak Guru / Staff tanpa batas jumlah.",
        "kategori": "guru",
        "icon": "fa-briefcase",
        "badge": "Multipersonel",
        "template": "3. Surat Tugas-smada.docx",
        "default_kode": "800.1.11.1",
        "signer": "kepsek",
        "person_mode": "multiple",
        "fields": [
            {
                "name": "dasar",
                "label": "Dasar Perintah",
                "type": "textarea",
                "rows": 3,
                "max_length": 1000,
            },
            {"name": "tanggal_mulai", "label": "Tanggal Tugas", "type": "date"},
            {"name": "tanggal_selesai", "label": "Sampai Tanggal", "type": "date"},
            {
                "name": "waktu",
                "label": "Waktu",
                "type": "text",
                "required": False,
                "placeholder": "cth: 07.30 WIB - selesai",
                "max_length": 120,
            },
            {
                "name": "tempat_kegiatan",
                "label": "Tempat Pelaksanaan",
                "type": "text",
                "required": False,
                "max_length": 300,
            },
            {
                "name": "keperluan",
                "label": "Untuk / Uraian Perintah",
                "type": "textarea",
                "rows": 4,
                "max_length": 1500,
            },
        ],
    },
    "surat_keterangan_guru": {
        "label": "Surat Keterangan Resmi",
        "deskripsi": "Surat keterangan aktif / penugasan resmi dari Kepala Sekolah.",
        "kategori": "guru",
        "icon": "fa-file-signature",
        "badge": "Keterangan",
        "template": "11. Surat Keterangan-smada.docx",
        "default_kode": "800.1.11",
        "signer": "kepsek",
        "fields": [
            {"name": "tanggal_mulai", "label": "Tanggal Keterangan", "type": "date"},
            {
                "name": "keperluan",
                "label": "Menerangkan Bahwa",
                "type": "text",
                "max_length": 500,
            },
        ],
    },
    "izin_murid": {
        "label": "Surat Izin Tidak Masuk",
        "deskripsi": "Pemberitahuan izin tidak masuk sekolah dari orang tua / wali murid.",
        "kategori": "murid",
        "icon": "fa-user-graduate",
        "badge": "Izin Siswa",
        "template": "izin_murid.docx",
        "default_kode": "400.3.8.9",
        "signer": "wali",
        "fields": [
            {"name": "nama_wali", "label": "Nama Orang Tua/Wali", "type": "text", "max_length": 120},
            {"name": "tanggal_mulai", "label": "Tanggal Mulai Izin", "type": "date"},
            {"name": "tanggal_selesai", "label": "Tanggal Selesai Izin", "type": "date"},
            {
                "name": "keperluan",
                "label": "Keperluan/Alasan",
                "type": "text",
                "max_length": 300,
            },
        ],
    },
    "dispensasi_murid": {
        "label": "Surat Dispensasi Kegiatan",
        "deskripsi": "Izin dispensasi mengikuti kegiatan lomba, OSIS, atau dinas luar.",
        "kategori": "murid",
        "icon": "fa-award",
        "badge": "Dispensasi",
        "template": "dispensasi_murid.docx",
        "default_kode": "400.3.8.10",
        "signer": "kepsek",
        "person_mode": "multiple",
        "max_people": 3,
        "fields": [
            {"name": "nama_kegiatan", "label": "Nama Kegiatan", "type": "text", "max_length": 200},
            {"name": "penyelenggara", "label": "Penyelenggara", "type": "text", "max_length": 200},
            {"name": "tempat_kegiatan", "label": "Tempat Kegiatan", "type": "text", "max_length": 200},
            {"name": "tanggal_mulai", "label": "Tanggal Mulai", "type": "date"},
            {"name": "tanggal_selesai", "label": "Tanggal Selesai", "type": "date"},
            {
                "name": "keperluan",
                "label": "Uraian / Keperluan",
                "type": "text",
                "default": "Mengikuti kegiatan sebagaimana tersebut di atas",
                "max_length": 500,
            },
        ],
    },
    "surat_pengantar_umum": {
        "label": "Surat Pengantar",
        "deskripsi": "Pengantar satu dokumen atau barang kepada instansi tujuan.",
        "kategori": "umum",
        "icon": "fa-paper-plane",
        "badge": "Administrasi",
        "template": "surat_pengantar_umum.docx",
        "default_kode": "000",
        "signer": "kepsek",
        "person_mode": "none",
        "fields": [
            {"name": "tujuan", "label": "Tujuan / Penerima", "type": "textarea", "rows": 2, "max_length": 300},
            {"name": "alamat_tujuan", "label": "Alamat Tujuan", "type": "textarea", "rows": 2, "max_length": 300},
            {"name": "jenis_barang", "label": "Jenis Dokumen / Barang", "type": "textarea", "rows": 3, "max_length": 700},
            {"name": "jumlah_barang", "label": "Jumlah", "type": "text", "placeholder": "cth: 1 berkas", "max_length": 80},
            {
                "name": "keterangan_pengantar",
                "label": "Keterangan",
                "type": "textarea",
                "rows": 3,
                "default": "Dikirim dengan hormat, agar mendapat penyelesaian sebagaimana mestinya.",
                "max_length": 700,
            },
        ],
    },
    "surat_pengantar_cuti_guru": {
        "label": "Surat Pengantar Cuti",
        "deskripsi": "Pengantar usulan cuti Guru / Staff kepada instansi kepegawaian.",
        "kategori": "guru",
        "icon": "fa-envelope-open-text",
        "badge": "Kepegawaian",
        "template": "surat_pengantar_cuti_guru.docx",
        "default_kode": "800.1.11.4",
        "signer": "kepsek",
        "fields": [
            {"name": "tujuan", "label": "Tujuan / Penerima", "type": "textarea", "rows": 2, "max_length": 300},
            {"name": "alamat_tujuan", "label": "Alamat Tujuan", "type": "textarea", "rows": 2, "max_length": 300},
            {
                "name": "jenis_cuti",
                "label": "Jenis Cuti",
                "type": "select",
                "options": ["Cuti Tahunan", "Cuti Sakit", "Cuti Melahirkan", "Cuti Besar", "Cuti Alasan Penting"],
            },
            {"name": "jumlah_barang", "label": "Jumlah Berkas", "type": "text", "default": "1 berkas", "max_length": 80},
            {
                "name": "keterangan_pengantar",
                "label": "Keterangan",
                "type": "textarea",
                "rows": 3,
                "default": "Dikirim dengan hormat, agar mendapat penyelesaian sebagaimana mestinya.",
                "max_length": 700,
            },
        ],
    },
    "permohonan_penceramah": {
        "label": "Permohonan Penceramah",
        "deskripsi": "Permohonan kesediaan penceramah untuk kegiatan sekolah.",
        "kategori": "umum",
        "icon": "fa-microphone-lines",
        "badge": "Permohonan",
        "template": "permohonan_penceramah.docx",
        "default_kode": "000",
        "signer": "kepsek",
        "person_mode": "none",
        "fields": [
            {"name": "sifat", "label": "Sifat", "type": "text", "default": "Biasa", "max_length": 80},
            {"name": "lampiran", "label": "Lampiran", "type": "text", "default": "-", "max_length": 80},
            {"name": "perihal", "label": "Perihal", "type": "text", "default": "Permohonan Penceramah", "max_length": 200},
            {"name": "penerima", "label": "Nama / Jabatan Penerima", "type": "text", "max_length": 200},
            {"name": "alamat_penerima", "label": "Alamat Penerima", "type": "textarea", "rows": 2, "default": "di Tempat", "max_length": 300},
            {"name": "latar_kegiatan", "label": "Latar Belakang / Tujuan Kegiatan", "type": "textarea", "rows": 4, "max_length": 1200},
            {"name": "hari", "label": "Hari", "type": "text", "max_length": 40},
            {"name": "tanggal_kegiatan", "label": "Tanggal Kegiatan", "type": "date"},
            {"name": "waktu", "label": "Waktu", "type": "text", "max_length": 120},
            {"name": "tempat_kegiatan", "label": "Tempat", "type": "text", "max_length": 300},
        ],
    },
    "surat_keterangan_kehilangan_murid": {
        "label": "Surat Keterangan Kehilangan",
        "deskripsi": "Keterangan resmi kehilangan kartu atau dokumen milik siswa.",
        "kategori": "murid",
        "icon": "fa-id-card-clip",
        "badge": "Keterangan Siswa",
        "template": "surat_keterangan_kehilangan_murid.docx",
        "default_kode": "400.3.8.8",
        "signer": "kepsek",
        "fields": [
            {"name": "barang_hilang", "label": "Kartu / Dokumen yang Hilang", "type": "text", "default": "Kartu PIP ATM BNI", "max_length": 200},
            {"name": "tempat_tanggal_lahir", "label": "Tempat, Tanggal Lahir", "type": "text", "max_length": 200},
            {
                "name": "jenis_kelamin_lengkap",
                "label": "Jenis Kelamin",
                "type": "select",
                "options": ["Laki-Laki", "Perempuan"],
            },
            {"name": "nomor_rekening", "label": "Nomor Rekening", "type": "text", "max_length": 80},
            {"name": "nama_ibu_kandung", "label": "Nama Ibu Kandung", "type": "text", "max_length": 200},
            {
                "name": "keperluan",
                "label": "Tujuan Penggunaan Surat",
                "type": "textarea",
                "rows": 4,
                "default": "Digunakan untuk pengurusan penggantian kartu atau dokumen yang hilang.",
                "max_length": 1000,
            },
        ],
    },
    "surat_rekomendasi_murid": {
        "label": "Surat Rekomendasi Siswa",
        "deskripsi": "Rekomendasi satu atau banyak siswa untuk lomba atau kegiatan.",
        "kategori": "murid",
        "icon": "fa-medal",
        "badge": "Multipersonel",
        "template": "surat_rekomendasi_murid.docx",
        "default_kode": "400.3.8.6",
        "signer": "kepsek",
        "person_mode": "multiple",
        "fields": [
            {"name": "nama_kegiatan", "label": "Nama Kegiatan", "type": "textarea", "rows": 3, "max_length": 500},
            {"name": "guru_pendamping", "label": "Nama Guru Pendamping", "type": "text", "max_length": 200},
            {"name": "nip_guru_pendamping", "label": "NIP Guru Pendamping", "type": "text", "required": False, "max_length": 40},
            {"name": "email_guru_pendamping", "label": "Email Guru Pendamping", "type": "text", "required": False, "max_length": 200},
            {"name": "telepon_guru_pendamping", "label": "Nomor HP Guru Pendamping", "type": "text", "required": False, "max_length": 80},
            {
                "name": "kontak_peserta",
                "label": "Kontak Peserta (Opsional)",
                "type": "textarea",
                "rows": 4,
                "required": False,
                "placeholder": "Tuliskan email/nomor HP tiap peserta bila dipersyaratkan.",
                "max_length": 1500,
            },
            {
                "name": "keperluan",
                "label": "Keterangan / Persyaratan",
                "type": "textarea",
                "rows": 3,
                "default": "Dibuat sebagai salah satu persyaratan pendaftaran kegiatan.",
                "max_length": 1000,
            },
        ],
    },
    "undangan_umum": {
        "label": "Surat Undangan",
        "deskripsi": "Undangan resmi untuk penerima umum, komite, atau mitra sekolah.",
        "kategori": "umum",
        "icon": "fa-envelope",
        "badge": "Undangan",
        "template": "undangan_umum.docx",
        "default_kode": "000",
        "signer": "kepsek",
        "person_mode": "none",
        "fields": [
            {"name": "sifat", "label": "Sifat", "type": "text", "default": "Biasa", "max_length": 80},
            {"name": "lampiran", "label": "Lampiran", "type": "text", "default": "-", "max_length": 80},
            {"name": "perihal", "label": "Hal", "type": "text", "default": "Undangan", "max_length": 200},
            {"name": "penerima", "label": "Penerima Undangan", "type": "textarea", "rows": 2, "max_length": 400},
            {"name": "alamat_penerima", "label": "Alamat Penerima", "type": "textarea", "rows": 2, "default": "di Tempat", "max_length": 300},
            {"name": "hari", "label": "Hari", "type": "text", "max_length": 40},
            {"name": "tanggal_kegiatan", "label": "Tanggal Kegiatan", "type": "date"},
            {"name": "waktu", "label": "Waktu", "type": "text", "max_length": 120},
            {"name": "tempat_kegiatan", "label": "Tempat", "type": "text", "max_length": 300},
            {"name": "acara", "label": "Acara", "type": "textarea", "rows": 4, "max_length": 1000},
        ],
    },
}
